In [1]:
import numpy as np

# Functions

#### arange()

In [2]:
np.arange(10) #arange([start,] stop[, step,], dtype=None, *, like=None)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [4]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
np.arange(20,10) #1st arg<2nd arg

array([], dtype=int32)

In [6]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [7]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [9]:
np.arange(0,10,5,1) #cant pass 4 arguments

TypeError: Cannot interpret '1' as a data type

#### zeros()

In [10]:
np.zeros(3) #zeros(shape, dtype=float, order='C', *, like=None)

array([0., 0., 0.])

In [11]:
np.zeros(10) #parameter tuning->system by default gives parameter

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(5,dtype=int) #hyperparameter tuning->user defines/changes the parameter

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2,2),dtype=int) #2d array

array([[0, 0],
       [0, 0]])

In [14]:
np.zeros((2,6)) #2rows*6columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros((5,10),dtype=int) #nd array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### ones()

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [18]:
np.ones((5,4),dtype=int) #5rows*4columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### random()

In [19]:
np.random.rand(5) #it gives o/p between 0-1

array([0.07387969, 0.74814021, 0.76913577, 0.8316839 , 0.54744859])

In [20]:
np.random.rand(2,5)

array([[0.61408654, 0.70336423, 0.92223473, 0.27790013, 0.28682153],
       [0.80469061, 0.8683976 , 0.7601349 , 0.51949623, 0.3374311 ]])

In [21]:
np.random.randint(10)#randint(low, high=None, size=None, dtype=int) Return random integers from `low` (inclusive) to `high` (exclusive).
# low considered as '0' to 9 random number

4

In [22]:
np.random.randint(5,50) #random number between 5 and 49

17

In [23]:
np.random.randint(0,100,15) #15 numbers

array([95, 86, 67, 46, 84, 90, 14, 89, 12, 83, 29, 55, 10, 97,  8])

In [24]:
np.random.randint(0,100,(10,10)) #10*10 array

array([[84, 15, 39, 67, 49, 68, 81, 11, 77, 18],
       [21, 53, 85, 82,  8,  0,  6, 38, 35, 20],
       [ 0, 83, 44, 67, 32, 24, 82,  4, 16, 13],
       [88,  0, 25, 26, 40, 90, 82, 58,  7, 84],
       [88, 12, 40, 59, 25, 23, 68, 16, 51,  6],
       [ 6, 33, 86, 60,  2, 81, 92, 81, 62, 70],
       [36, 77, 39, 48, 54, 89, 26, 64, 23, 89],
       [62, 76, 51, 72,  7, 53, 37, 67, 17,  9],
       [13, 63, 38, 18, 92, 59,  0, 38, 45, 14],
       [66, 30, 75, 32, 25, 52, 95, 87, 87, 75]])

#### reshape()

In [25]:
arr=np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr.reshape(7,2) #Returns an array containing the same data with a new shape.

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [27]:
arr.reshape(8,1) #the reshape size should be exacty same as array elements size

ValueError: cannot reshape array of size 14 into shape (8,1)

In [28]:
arr.reshape(14,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [29]:
arr2=np.random.randint(0,100,(5,4))
arr2

array([[23, 74, 88, 93],
       [97, 51, 21, 41],
       [83, 54, 35, 67],
       [35, 80,  8, 87],
       [26, 72, 70,  8]])

In [30]:
arr2.reshape(10,2)

array([[23, 74],
       [88, 93],
       [97, 51],
       [21, 41],
       [83, 54],
       [35, 67],
       [35, 80],
       [ 8, 87],
       [26, 72],
       [70,  8]])