# Numpy
- NumPy is a powerful library in Python used for numerical computations. It's particularly good at handling large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them.

In [1]:
import numpy as np

In [2]:
np.__version__ #to check version "__.version__"

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

### Creating Arrays

In [4]:
my_list=[0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [5]:
arr=np.array(my_list) #convert list to array
arr

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

#### arange()

In [7]:
np.arange(15) #arange([start,] stop[, step,], dtype=None, *, like=None)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(0,20,2,dtype=float) #dtype to mention the data type

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [9]:
np.arange(10,dtype=bool)

TypeError: arange() is only supported for booleans when the result has at most length 2.

In [10]:
np.arange(2,dtype=bool)

array([False,  True])

In [11]:
np.arange(10,dtype=str)

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.