In [1]:
import numpy as np

In [2]:
np.random.randint(10,30,(10,10))

array([[20, 12, 24, 15, 11, 13, 23, 25, 13, 18],
       [23, 17, 11, 17, 15, 20, 29, 14, 22, 22],
       [28, 29, 27, 12, 13, 15, 25, 28, 17, 27],
       [25, 13, 25, 24, 20, 24, 22, 21, 21, 10],
       [21, 17, 14, 20, 20, 28, 23, 19, 15, 16],
       [17, 29, 18, 20, 18, 19, 25, 20, 12, 10],
       [25, 10, 21, 16, 28, 16, 10, 16, 17, 12],
       [10, 27, 28, 28, 22, 20, 18, 15, 22, 10],
       [26, 27, 21, 16, 26, 24, 15, 11, 27, 21],
       [23, 14, 21, 25, 25, 29, 18, 21, 19, 15]])

In [3]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Slicing In matrix

In [6]:
a=np.random.randint(10,20,(5,4))

In [7]:
a

array([[17, 16, 15, 12],
       [12, 13, 16, 14],
       [13, 10, 18, 15],
       [18, 10, 16, 13],
       [17, 19, 19, 18]])

In [8]:
type(a)

numpy.ndarray

In [9]:
a[:] #':'slicing 

array([[17, 16, 15, 12],
       [12, 13, 16, 14],
       [13, 10, 18, 15],
       [18, 10, 16, 13],
       [17, 19, 19, 18]])

In [10]:
a[1:3] #prints 1 t0 3-1 rows

array([[12, 13, 16, 14],
       [13, 10, 18, 15]])

In [11]:
a[0:3] #0 t0 2 rows

array([[17, 16, 15, 12],
       [12, 13, 16, 14],
       [13, 10, 18, 15]])

In [12]:
a[1,2] #1row,2column element

16

In [13]:
a

array([[17, 16, 15, 12],
       [12, 13, 16, 14],
       [13, 10, 18, 15],
       [18, 10, 16, 13],
       [17, 19, 19, 18]])

In [14]:
a[1,-1] #1row,-1column i.e lastcoulmn backward slicing

14

In [15]:
a[2:3] #2 row

array([[13, 10, 18, 15]])

In [16]:
a

array([[17, 16, 15, 12],
       [12, 13, 16, 14],
       [13, 10, 18, 15],
       [18, 10, 16, 13],
       [17, 19, 19, 18]])

In [17]:
a[0:-2]

array([[17, 16, 15, 12],
       [12, 13, 16, 14],
       [13, 10, 18, 15]])

In [18]:
a[-4:4]

array([[12, 13, 16, 14],
       [13, 10, 18, 15],
       [18, 10, 16, 13]])

In [19]:
b=np.random.randint(10,50,(10,10))

In [20]:
b

array([[27, 45, 19, 28, 38, 34, 48, 30, 44, 12],
       [19, 48, 33, 39, 48, 14, 31, 35, 37, 16],
       [16, 17, 12, 33, 25, 16, 25, 14, 19, 15],
       [17, 45, 41, 32, 47, 41, 28, 33, 37, 36],
       [26, 38, 40, 14, 10, 15, 18, 18, 26, 12],
       [13, 32, 27, 49, 11, 16, 11, 47, 13, 16],
       [10, 42, 16, 12, 44, 47, 48, 49, 47, 43],
       [24, 42, 15, 19, 37, 21, 11, 19, 46, 36],
       [46, 38, 35, 20, 15, 34, 24, 40, 21, 49],
       [18, 38, 36, 29, 18, 29, 13, 34, 45, 14]])

In [21]:
arr=np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
b[::-1] #reverse an matrixx

array([[18, 38, 36, 29, 18, 29, 13, 34, 45, 14],
       [46, 38, 35, 20, 15, 34, 24, 40, 21, 49],
       [24, 42, 15, 19, 37, 21, 11, 19, 46, 36],
       [10, 42, 16, 12, 44, 47, 48, 49, 47, 43],
       [13, 32, 27, 49, 11, 16, 11, 47, 13, 16],
       [26, 38, 40, 14, 10, 15, 18, 18, 26, 12],
       [17, 45, 41, 32, 47, 41, 28, 33, 37, 36],
       [16, 17, 12, 33, 25, 16, 25, 14, 19, 15],
       [19, 48, 33, 39, 48, 14, 31, 35, 37, 16],
       [27, 45, 19, 28, 38, 34, 48, 30, 44, 12]])

In [23]:
b[::-2]

array([[18, 38, 36, 29, 18, 29, 13, 34, 45, 14],
       [24, 42, 15, 19, 37, 21, 11, 19, 46, 36],
       [13, 32, 27, 49, 11, 16, 11, 47, 13, 16],
       [17, 45, 41, 32, 47, 41, 28, 33, 37, 36],
       [19, 48, 33, 39, 48, 14, 31, 35, 37, 16]])

In [24]:
b[0:9:2]

array([[27, 45, 19, 28, 38, 34, 48, 30, 44, 12],
       [16, 17, 12, 33, 25, 16, 25, 14, 19, 15],
       [26, 38, 40, 14, 10, 15, 18, 18, 26, 12],
       [10, 42, 16, 12, 44, 47, 48, 49, 47, 43],
       [46, 38, 35, 20, 15, 34, 24, 40, 21, 49]])

In [25]:
b

array([[27, 45, 19, 28, 38, 34, 48, 30, 44, 12],
       [19, 48, 33, 39, 48, 14, 31, 35, 37, 16],
       [16, 17, 12, 33, 25, 16, 25, 14, 19, 15],
       [17, 45, 41, 32, 47, 41, 28, 33, 37, 36],
       [26, 38, 40, 14, 10, 15, 18, 18, 26, 12],
       [13, 32, 27, 49, 11, 16, 11, 47, 13, 16],
       [10, 42, 16, 12, 44, 47, 48, 49, 47, 43],
       [24, 42, 15, 19, 37, 21, 11, 19, 46, 36],
       [46, 38, 35, 20, 15, 34, 24, 40, 21, 49],
       [18, 38, 36, 29, 18, 29, 13, 34, 45, 14]])

In [26]:
b[6,:] #7th row

array([10, 42, 16, 12, 44, 47, 48, 49, 47, 43])

In [27]:
b[:,6] #7th column

array([48, 31, 25, 28, 18, 11, 48, 11, 24, 13])

In [28]:
b[:6] #0 to 5 rows

array([[27, 45, 19, 28, 38, 34, 48, 30, 44, 12],
       [19, 48, 33, 39, 48, 14, 31, 35, 37, 16],
       [16, 17, 12, 33, 25, 16, 25, 14, 19, 15],
       [17, 45, 41, 32, 47, 41, 28, 33, 37, 36],
       [26, 38, 40, 14, 10, 15, 18, 18, 26, 12],
       [13, 32, 27, 49, 11, 16, 11, 47, 13, 16]])

In [29]:
b[6:] #6 to remaining rows

array([[10, 42, 16, 12, 44, 47, 48, 49, 47, 43],
       [24, 42, 15, 19, 37, 21, 11, 19, 46, 36],
       [46, 38, 35, 20, 15, 34, 24, 40, 21, 49],
       [18, 38, 36, 29, 18, 29, 13, 34, 45, 14]])

In [30]:
b

array([[27, 45, 19, 28, 38, 34, 48, 30, 44, 12],
       [19, 48, 33, 39, 48, 14, 31, 35, 37, 16],
       [16, 17, 12, 33, 25, 16, 25, 14, 19, 15],
       [17, 45, 41, 32, 47, 41, 28, 33, 37, 36],
       [26, 38, 40, 14, 10, 15, 18, 18, 26, 12],
       [13, 32, 27, 49, 11, 16, 11, 47, 13, 16],
       [10, 42, 16, 12, 44, 47, 48, 49, 47, 43],
       [24, 42, 15, 19, 37, 21, 11, 19, 46, 36],
       [46, 38, 35, 20, 15, 34, 24, 40, 21, 49],
       [18, 38, 36, 29, 18, 29, 13, 34, 45, 14]])

In [31]:
b[0:2,0:3] #specifed row,column

array([[27, 45, 19],
       [19, 48, 33]])

In [32]:
b[5,5] #6th row*6th column element

16

## Operations

In [33]:
arr

array([0, 1, 2, 3, 4, 5])

In [34]:
id(arr)

2146108320112

In [35]:
arr.max()

5

In [36]:
arr.min()

0

In [37]:
arr.mean()

2.5

In [38]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [39]:
#to execute median we should import all functions of numpy
from numpy import *

In [40]:
arr

array([0, 1, 2, 3, 4, 5])

In [41]:
median(arr)

2.5

In [42]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

### Masking

In [45]:
a=np.arange(1,101).reshape(10,10)

In [46]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [47]:
a>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [48]:
a[a>50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [49]:
a[a<50]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])