#### Uses Of Numpy
https://i0.wp.com/techvidvan.com/tutorials/wp-content/uploads/sites/2/2020/07/Uses-of-NumPy-1.jpg?resize=768%2C542&ssl=1

### 1. Array Creation Functions

In [1]:
import numpy as np

In [2]:
#Creating array from list
l=[1,2.0,True,'tharun',1+2j]
np.array(l)

array(['1', '2.0', 'True', 'tharun', '(1+2j)'], dtype='<U64')

In [3]:
#creating using arange()->Return evenly spaced values within a given interval.
np.arange(0,25,2) #values from 0-24 with step 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [4]:
#creating using linspace()->Return evenly spaced numbers over a specified interval.
np.linspace(0,1,5) #5 values evenly spaced between 0-1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.linspace(0,10,11) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
#using zeros()->Return a new array of given shape and type, filled with zeros.
np.zeros((2,5)) #by default float type

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((5,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [8]:
#using ones()->Return a new array of given shape and type, filled with ones.
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.ones((5,9),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
#using eye()->Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
np.eye(5,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

### 2. Array Manipulation Functions

#### Reshape an array

In [12]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr.reshape(5,2) #Returns an array containing the same data with a new shape.

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Flatten an array

In [15]:
a=np.array([[1,2],[5,6]])
a

array([[1, 2],
       [5, 6]])

In [16]:
#Return a flattened array.
a.ravel()

array([1, 2, 5, 6])

In [17]:
b=np.eye(3,dtype=int)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
b.ravel() #Converts an array to 1D array

array([1, 0, 0, 0, 1, 0, 0, 0, 1])

#### Transpose an array

In [19]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a.transpose() #transfers rows-columns;columns-rows

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Stack arrays Vertically

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
np.vstack((a,b))#Stack arrays in sequence vertically (row wise).

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 3. Mathametical Functions

#### Add 

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.add(a,1.2) #Add arguments ea,1lement-wise.

array([[ 2.2,  3.2,  4.2],
       [ 5.2,  6.2,  7.2],
       [ 8.2,  9.2, 10.2]])

#### Square

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.square(a) #Return the element-wise square of the input.

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

#### Sqrt

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.sqrt(a) #Return the non-negative square-root of an array, element-wise.

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

#### Dot Product

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
b=np.add(b,2)
b

array([[3, 2, 2],
       [2, 3, 2],
       [2, 2, 3]])

In [32]:
np.dot(a,b) #Dot product of two arrays.

array([[13, 14, 15],
       [34, 35, 36],
       [55, 56, 57]])

### 4. Statistical Functions

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
#mean
print(np.mean(a))#Compute the arithmetic mean along the specified axis.
                 #The default is to compute the mean of the flattened array.
print(np.mean(a,axis=0)) #column wise
print(np.mean(a,axis=1)) #row wise

5.0
[4. 5. 6.]
[2. 5. 8.]


In [35]:
#median
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [36]:
#standard deviation
print(np.std(a))
print(np.std(a,axis=0))
print(np.std(a,axis=1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [37]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
#Min
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

1
[1 2 3]
[1 4 7]


In [39]:
#Max
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))

9
[7 8 9]
[3 6 9]


### 5. LinearAlgebra Functions

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
#Determinant
np.linalg.det(a) #Compute the determinant of an array.

-9.51619735392994e-16

In [42]:
#Inverse
np.linalg.inv(a) #Compute the (multiplicative) inverse of a matrix.

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])


### 6. RandomSampling Functions

In [43]:
#random values
np.random.rand(4,2) #between 0-1 float values in given dimensions

array([[0.85209563, 0.76532823],
       [0.74422928, 0.40972838],
       [0.53378187, 0.56633738],
       [0.40971798, 0.0938301 ]])

In [44]:
np.random.randint(0,100,5)# 5 random integers between 0-99

array([76, 23, 60, 74,  1])

In [45]:
#if we set random.seed to 0 once genarated values dont change any times we run
np.random.seed(0)
np.random.randint(0,100,5)

array([44, 47, 64, 67, 67])

### 7. Boolean&Logical Functions

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.all(a) #Test whether all array elements along a given axis evaluate to True.

True

In [48]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.all(a)

False

In [50]:
np.any(a) #Test whether any array element along a given axis evaluates to True.

True

### 8. Set Operations

In [51]:
a=np.array([3,4,5,1,2])
b=np.array([6,7,3,4,5])

In [52]:
#intersection
np.intersect1d(a,b) #Find the intersection of two arrays.Return the sorted, unique values that are in both of the input arrays.

array([3, 4, 5])

In [53]:
#union
np.union1d(a,b) #Find the union of two arrays.Return the unique, sorted array of values that are in either of the two input arrays.

array([1, 2, 3, 4, 5, 6, 7])

### 9. ArrayAttribute Functions

In [54]:
a

array([3, 4, 5, 1, 2])

In [55]:
a.shape #shape of array

(5,)

In [56]:
a.size #no.of elements in array

5

In [57]:
a.ndim #dimension of array

1

In [58]:
a.dtype #type of array elements

dtype('int32')

### 10. Other Functions

In [59]:
a

array([3, 4, 5, 1, 2])

In [60]:
b=a #intializing b to a

In [61]:
b

array([3, 4, 5, 1, 2])

In [62]:
copy=np.copy(a) #to copy an array

In [63]:
copy

array([3, 4, 5, 1, 2])

In [64]:
a.nbytes #bytes of an array

20

In [65]:
np.shares_memory(a,copy) #to find both sares memeory 

False

In [66]:
np.shares_memory(a,b) #as we shared memory directly

True